name: Build Android APK

on: [workflow_dispatch]

jobs:
#  test:
#    name: Run tests
#    runs-on: ubuntu-20.04
#    steps:
#      - name: Checkout release branch
#        uses: actions/checkout@v2
#
#      - name: Set up JDK
#        uses: actions/setup-java@v2
#        with:
#          distribution: temurin
#          java-version: 11
#
#      - name: Run tests
#        run: ./gradlew test

  build:
    name: Generate APK
#    needs: test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout release branch
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk
