name: Run Unit Tests

on: [workflow_dispatch]

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout release branch
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Run tests
        run: ./gradlew test
